# Generated by Django 5.0.6 on 2024-07-23 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CodingLanguage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang_name', models.CharField(max_length=50)),
                ('lang_timespent', models.FloatField()),
                ('lang_proj_worked', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CodingTool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tool_name', models.CharField(max_length=50)),
                ('tool_timespent', models.FloatField()),
                ('tool_project_worked', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='GroupProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gproj_name', models.CharField(max_length=50)),
                ('gproj_desc', models.CharField(max_length=300)),
                ('gproj_lang_utilized', models.CharField(max_length=300)),
                ('gproj_tools_used', models.CharField(max_length=300)),
                ('gproj_timespent', models.FloatField()),
                ('gproj_github_link', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='IndividualAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iassign_name', models.CharField(max_length=50)),
                ('iassign_desc', models.CharField(max_length=300)),
                ('iassign_lang_utilized', models.CharField(max_length=300)),
                ('iassign_tools_used', models.CharField(max_length=300)),
                ('iassign_timespent', models.FloatField()),
                ('iassign_github_link', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='IndividualProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iproj_name', models.CharField(max_length=50)),
                ('iproj_desc', models.CharField(max_length=300)),
                ('iproj_lang_utilized', models.CharField(max_length=300)),
                ('iproj_tools_used', models.CharField(max_length=300)),
                ('iproj_timespent', models.FloatField()),
                ('iproj_github_link', models.URLField()),
            ],
        ),
    ]
